[package]
name = "icicle-stark252"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Rust wrapper for the CUDA implementation of stark252 prime field by Ingonyama"
homepage.workspace = true
repository.workspace = true

[dependencies]
icicle-core = { workspace = true }
icicle-cuda-runtime = { workspace = true }

[build-dependencies]
cmake = "0.1.50"

[dev-dependencies]
lambdaworks-math = "0.6.0"
#icicle-core = { path = "../../icicle-core", features = ["arkworks"] }

[features]
default = []
devmode = ["icicle-core/devmode"]
