[package]
name = "icicle-babybear"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
icicle-core =  {workspace = true }
icicle-runtime = { workspace = true }

[dev-dependencies]
criterion = "0.3"
serial_test = "3.0.0"
risc0-core = "0.21.0"
risc0-zkp = "0.21.0"

[build-dependencies]
cmake = "0.1.50"
