[package]
name = "icicle-cuda-runtime"
version = "1.3.0"
edition = "2021"
authors = [ "Ingonyama" ]
description = "Ingonyama's Rust wrapper of CUDA runtime"
homepage = "https://www.ingonyama.com"
repository = "https://github.com/ingonyama-zk/icicle"

[dependencies]
bitflags = "1.3"

[build-dependencies]
bindgen = "*"
