[package]
name = "icicle-bls12-381"
version = "1.2.0"
edition = "2021"
authors = [ "Ingonyama" ]
description = "Rust wrapper for the CUDA implementation of BLS12-381 pairing friendly elliptic curve by Ingonyama"
homepage = "https://www.ingonyama.com"
repository = "https://github.com/ingonyama-zk/icicle"

[dependencies]
icicle-core = { path = "../../icicle-core" }
icicle-cuda-runtime = { path = "../../icicle-cuda-runtime" }
ark-bls12-381 = { version = "0.4.0", optional = true }

[build-dependencies]
cmake = "0.1.50"

[dev-dependencies]
ark-bls12-381 = "0.4.0"
ark-std = "0.4.0"
ark-ff = "0.4.0"
ark-ec = "0.4.0"
ark-poly = "0.4.0"
icicle-core = { path = "../../icicle-core", features = ["arkworks"] }
icicle-bls12-381 = { path = ".", features = ["arkworks"] }

[features]
default = []
g2 = ["icicle-core/g2"]
arkworks = ["ark-bls12-381", "icicle-core/arkworks"]
