[package]
name = "icicle-bls12-377"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Rust wrapper for the CUDA implementation of BLS12-377 pairing friendly elliptic curve by Ingonyama"
homepage.workspace = true
repository.workspace = true

[dependencies]
icicle-core = { workspace = true }
icicle-cuda-runtime = { workspace = true }
ark-bls12-377 = { version = "0.4.0", optional = true }
criterion = "0.3"

[build-dependencies]
cmake = "0.1.50"

[dev-dependencies]
criterion = "0.3"
ark-bls12-377 = "0.4.0"
ark-std = "0.4.0"
ark-ff = "0.4.0"
ark-ec = "0.4.0"
ark-poly = "0.4.0"
icicle-core = { path = "../../icicle-core", features = ["arkworks"] }
icicle-bls12-377 = { path = ".", features = ["arkworks"] }
serial_test = "3.0.0"

[features]
default = []
bw6-761 = []
bw6-761-g2 = ["bw6-761"]
g2 = ["icicle-core/g2"]
ec_ntt = ["icicle-core/ec_ntt"]
devmode = ["icicle-core/devmode"]
arkworks = ["ark-bls12-377", "icicle-core/arkworks"]

[[bench]]
name = "ecntt"
harness = false

[[bench]]
name = "ntt"
harness = false

[[bench]]
name = "msm"
harness = false